//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Validation;
namespace XafTaskApp.Module.BusinessObjects
{
    public partial class invoice : XPLiteObject
    {
        int finvoice_id;
        [System.ComponentModel.DisplayName("Invoice ID")]
        [Key(true)]
        public int invoice_id
        {
            get { return finvoice_id; }
            set { SetPropertyValue<int>(nameof(invoice_id), ref finvoice_id, value); }
        }
        DateTime finvoice_date;
        [System.ComponentModel.DisplayName("Invoice Date")]
        [RuleRequiredField("InvoiceDateRequired", DefaultContexts.Save, "Invoice Date is required.")] // Required field
        public DateTime invoice_date
        {
            get { return finvoice_date; }
            set { SetPropertyValue<DateTime>(nameof(invoice_date), ref finvoice_date, value); }
        }
        customer fcustomer_id;
        [System.ComponentModel.DisplayName("Customer")]
        [Association(@"invoiceReferencescustomer")]
        [RuleRequiredField("InvoiceCustomerRequired", DefaultContexts.Save, "Customer is required.")] // Required field
        public customer customer_id
        {
            get { return fcustomer_id; }
            set { SetPropertyValue<customer>(nameof(customer_id), ref fcustomer_id, value); }
        }
        string finvoice_desc;
        [System.ComponentModel.DisplayName("Description")]
        [Size(500)]
        public string invoice_desc
        {
            get { return finvoice_desc; }
            set { SetPropertyValue<string>(nameof(invoice_desc), ref finvoice_desc, value); }
        }
        [Association(@"invoice_detailReferencesinvoice")]
        public XPCollection<invoice_detail> invoice_details { get { return GetCollection<invoice_detail>(nameof(invoice_details)); } }
        [Association(@"paymentReferencesinvoice")]
        public XPCollection<payment> payments { get { return GetCollection<payment>(nameof(payments)); } }
    }

}
